server:
  # 指定Tomcat端口
  port: 8010
spring:
  application:
    name: @project.description@
  boot:
    admin:
      client:
        url: http://localhost:8090
  jpa:
    # 让hibernate打印执行的SQL
    show-sql: true

eureka:
  instance:
    # 是否注册IP到eureka server，如不指定或设为false，那就会注册主机名到eureka server
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://user:pwd123123@localhost:8761/eureka/,http://user:pwd123123@localhost:8762/eureka/


logging:
  level:
    root: INFO
    # 配置日志级别，让hibernate打印出执行的SQL参数
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE

#监控配置
management:
  endpoint:
    health:
      # 是否展示健康检查详情
      show-details: always
  endpoints:
    web:
      exposure:
        # 暴露metrics端点，如需暴露多个，用,分隔；如需暴露所有端点，用'*'
        include: '*'
